stages:
- "test"

.test-template:
  stage: test
  image: python:3.9.6-slim-buster
  before_script:
  - pip install poetry==1.4.2
  - poetry config virtualenvs.create false
  - poetry install
  - |
    echo "MODELHUB_RELOAD=False" >> .env
    echo "MODELHUB_COSMOS_ENDPOINT=$MODELHUB_COSMOS_ENDPOINT" >> .env
    echo "MODELHUB_COSMOS_KEY=$MODELHUB_COSMOS_KEY" >> .env
    echo "MODELHUB_BLOB_ACCOUNT_URL=$MODELHUB_BLOB_ACCOUNT_URL" >> .env
    echo "MODELHUB_BLOB_SAS_TOKEN=$MODELHUB_BLOB_SAS_TOKEN" >> .env

black:
  extends:
  - .test-template
  script:
  - black --check .

pytest:
  extends:
  - .test-template
  script:
  - pytest -vv --junitxml=report.xml --cov="modelhub" .
  - coverage xml
  artifacts:
    when: always
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  after_script:
    - rm .env
